# Generated by Django 3.1 on 2020-08-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200816_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_counter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальноe число людей на перерыве')),
                ('lunch_counter', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальноe число людей на обеде')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
