# Generated by Django 3.1 on 2020-08-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
